global using Api.Data;
global using Api.Dtos.Dependent;
global using Api.Dtos.Employee;
global using Api.Extensions;
global using Api.Helper;
global using Api.Models;
global using Api.Services;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Annotations;
